version: '3'
services:

  hmongo:
    container_name: hmongo
    image: mongo:4.0.3
    command: mongod --bind_ip 0.0.0.0 --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: h
      MONGO_INITDB_ROOT_PASSWORD: my_password
    volumes:
    - ./data/mongo:/data/db/:rw
    ports:
    - 127.0.0.1:27017:27017
    restart: always

  hnginx:
    container_name: hnginx
    image: nginx:1.15.5-alpine
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
    - 80:80
    restart: always